[package]
name = "link_checker"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1"

config = { path = "../config" }
errors = { path = "../errors" }

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "rustls-tls"]

[dev-dependencies]
mockito = "0.28"
