title = "My site"
base_url = "https://replace-this-with-your-url.com"
compile_sass = true
generate_feed = true
theme = "sample"

taxonomies = [
    {name = "categories", feed = true},
    {name = "podcast_authors", feed = true},
]

ignored_content = ["*/ignored.md"]

[markdown]
highlight_code = true
extra_syntaxes = ["syntaxes"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
skip_prefixes = [
    "http://[2001:db8::]/",
]

skip_anchor_prefixes = [
    "https://github.com/rust-lang/rust/blob/",
]

[extra.author]
name = "Vincent Prouillet"
